/*
 * (C) Copyright 2007-2008 Michal Simek
 *
 * Michal SIMEK <monstr@monstr.eu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 *
 * CAUTION: This file is automatically generated by libgen.
 * Version: Xilinx EDK 14.6 EDK_P.68d
 * Generate by U-BOOT v4.00.c
 * Project description at http://www.monstr.eu/uboot/
 */

#define XILINX_BOARD_NAME	U-BOOT_BSP

/* Microblaze is microblaze_0 */
#define XILINX_USE_MSR_INSTR	1
#define XILINX_PVR		2
#define XILINX_FSL_NUMBER	0
#define XILINX_USE_ICACHE	1
#define XILINX_USE_DCACHE	1
#define XILINX_DCACHE_BYTE_SIZE	4096

/* Interrupt controller is xps_intc_0 */
#define XILINX_INTC_BASEADDR		0x81400000
#define XILINX_INTC_NUM_INTR_INPUTS	13

/* Timer pheriphery is xps_timer_0 */
#define XILINX_TIMER_BASEADDR	0x81402000
#define XILINX_TIMER_IRQ	6

/* System Timer Clock Frequency */
#define XILINX_CLOCK_FREQ	100000000

/* Uart console is rs232_uart_1 */
#define XILINX_UARTLITE_BASEADDR	0x81401000
#define XILINX_UARTLITE_BAUDRATE	115200
#define XILINX_UARTLITE_BASEADDR1	0x81408000

/* IIC pheriphery is i2c_eeprom */
#define XILINX_IIC_0_BASEADDR	0x81406000
#define XILINX_IIC_0_FREQ	100000
#define XILINX_IIC_0_BIT	0

/* GPIO is leds_8bit*/
#define XILINX_GPIO_BASEADDR	0x81405000

/* SDIO doesn't exist */

/* Main Memory is ddr2_sdram */
#define XILINX_RAM_START	0xc0000000
#define XILINX_RAM_SIZE		0x10000000

/* Flash Memory is flash */
#define XILINX_FLASH_START	0x82000000
#define XILINX_FLASH_SIZE	0x02000000

/* Sysace Controller is sysace_compactflash */
#define XILINX_SYSACE_BASEADDR	0x8140C000
#define XILINX_SYSACE_MEM_WIDTH	16

/* Ethernet controller is hard_ethernet_mac */
#define XILINX_LLTEMAC_BASEADDR			0x81500000
#define XILINX_LLTEMAC_SDMA_CTRL_BASEADDR	0x81410100
